export const itoThemes = [
  'Comida que você só comeria se estivesse morrendo de fome',
  'Melhor comida de domingo em família',
  'Lanche que vale a fila gigante',
  'Sobremesa que você repetiria três vezes',
  'Comida que parece ruim, mas é boa demais',
  'Bebida ideal para um dia extremamente quente',
  'Comida que você comeria todo dia sem enjoar',
  'Restaurante que você indicaria sem medo',
  'Comida que você pediria se fosse sua última refeição',
  'Comida que você só come por educação',

  'Filme que você não indicaria pra ninguém',
  'Filme ok para ver num domingo à tarde',
  'Filme que você assistiria de novo',
  'Filme que te deixou pensando por dias',
  'Série que você largou no segundo episódio',
  'Série que você fez maratona sem dormir',
  'Final de série mais satisfatório',
  'Personagem mais insuportável',
  'Personagem que você gostaria de ser',
  'Filme que todo mundo ama, mas você não entendeu',

  'Jogo que você desinstalou com raiva',
  'Jogo bom pra passar o tempo',
  'Jogo que você jogaria todo fim de semana',
  'Jogo que você considera uma obra de arte',
  'App que você usa por obrigação',
  'App que realmente facilita sua vida',
  'Tecnologia que parecia inútil, mas hoje é essencial',
  'Bug mais irritante',
  'Jogo que você recomendaria até pra quem não joga',

  'Situação levemente constrangedora',
  'Situação que dá vergonha alheia',
  'Situação que você queria sumir',
  'Situação que vira uma boa história depois',
  'Situação que arruina seu dia',
  'Situação que melhora seu dia',
  'Coisa que você faria por 100 reais',
  'Coisa que você nunca faria nem por dinheiro',
  'Situação que te deixa ansioso na hora',

  'Tarefa chata, mas necessária',
  'Trabalho que você faria só por pouco tempo',
  'Trabalho aceitável',
  'Trabalho dos sonhos',
  'Reunião que poderia ser um e-mail',
  'Chefe difícil de lidar',
  'Melhor chefe possível',
  'Coisa que todo adulto finge que sabe',
  'Responsabilidade que ninguém te avisou que existia',

  'Qualidade que passa despercebida',
  'Qualidade importante em um amigo',
  'Qualidade essencial em um relacionamento',
  'Red flag leve',
  'Red flag grave',
  'Atitude que te faz perder o interesse',
  'Atitude que te faz se apaixonar',
  'Tipo de pessoa difícil de conviver',
  'Tipo de pessoa que todo grupo precisa',

  'Coisa superestimada',
  'Coisa subestimada',
  'Coisa que piora com o tempo',
  'Coisa que melhora com o tempo',
  'Coisa que você defenderia até o fim',
  'Coisa que você mudaria no mundo',
  'Coisa que parece simples, mas não é',
  'Pequeno prazer da vida',
  'Grande conquista pessoal',
];
